name: Application Deployment

on:
  workflow_run:
    workflows: ["Infrastructure Deployment"]
    types:
      - completed

jobs:
  deploy-app:
    name: Deploy Application to Azure App Service
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Install dependencies and build the app
      - name: Install dependencies
        run: |
          cd app
          npm install

      # Zip the application for deployment
      - name: Zip Application
        run: |
          cd app
          zip -r ../app.zip .

      # Login to Azure using Service Principal credentials (from AZURE_CREDENTIALS)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.APP_SERVICE_NAME }}
          package: ./app.zip
