name: Infrastructure Deployment

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  terraform-deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0  # Ensure this matches your Terraform version

      # Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Terraform Init
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Terraform Validate
      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        working-directory: ./terraform
        id: plan
        run: terraform plan -out=tfplan

      # Terraform Apply
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan

      # Output the App Service Hostname
      - name: Output App Service Hostname
        working-directory: ./terraform
        run: |
          echo "App Service Hostname: $(terraform output -raw app_service_default_site_hostname)"
